version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master" # update on master to current dev branch

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master" # update on master to current dev branch

  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
    target-branch: "master" # update on master to current dev branch
