#!/bin/sh

echo "Running git-pre-commit script from composer.json"

# Use composer.phar or global composer
if [ ! -f ./composer.phar ]; then
	COMPOSER=$(which composer)
	if [ $? != 0 ]; then
		echo "Commit Blocked."
		echo "Pre-commit hook can't locate global composer or local composer.phar"
		echo "In an emergency, use 'git commit --no-verify' to skip."
		exit 1
	else
		composer git-pre-commit
		composer_exit_status=$?
	fi
else
	php composer.phar git-pre-commit
	composer_exit_status=$?
fi

if (($composer_exit_status > 0)); then
	echo "Commit Blocked."
	echo "Fix the errors and try to commit again."
	echo "In an emergency, use 'git commit --no-verify' to skip."
	exit 1
fi

exit 0
