#!/bin/sh

#### Runs PHP linter and PHP Code Sniffer on all staged files
#### Install the hook:  cp githooks/pre-commit .git/hooks/ && chmod +x .git/hooks/pre-commit
#### setting up phpcs:
# $ install composer to your system
#### make sure .composer/vendor/bin is in your path in your .bash_profile: export PATH="$HOME/.composer/vendor/bin:$PATH"
# $ composer global require "squizlabs/php_codesniffer=*"
# $ cd wherever-you-keep-projects
# $ git clone git@github.com:ucfcdl/fuelphp-phpcs.git
# $ ln -s wherever-you-keep-projects/fuelphp-phpcs/Standards/FuelPHP $HOME/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/FuelPHP
#### phpcs should show you the fuelphp standard:
# $ phpcs -i

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
	echo "Running Code Sniffer..."
	phpcs --standard=FuelPHP --encoding=utf-8 -n -p $FILES
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
fi

exit $?