#!/bin/sh

echo "Running git-pre-commit script from composer.json"
echo "In an emergency, use 'git commit --no-verify' to skip."

cd docker
set -e
set -o xtrace

DCTEST="docker-compose -f docker-compose.yml -f docker-compose.override.test.yml"

# run linter
source run_tests_lint.sh

# install widgets and run tests
source run_tests.sh

# turn off failure stop on error
set +e

composer_exit_status=$?

if (($composer_exit_status > 0)); then
	echo "Commit Blocked."
	echo "Fix the errors and try to commit again."
	echo "In an emergency, use 'git commit --no-verify' to skip."
	exit 1
fi

exit 0
