server {
	listen *:80;
	server_name default;

	client_max_body_size 20M;

	root /var/www/html/staticfiles;
	index index.html;

	location / {
		try_files $uri @handler;
		expires 30d;
	}

	location @handler {
		proxy_pass http://python:8001;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_read_timeout    300;
		proxy_send_timeout    300;
		proxy_connect_timeout 300;

		proxy_redirect off;
	}

	# Automatically check to see if an image theme override exists, then fall back to default
	location ~/static/img/(.*)$ {
		try_files /theme/img/$1 /img/$1;
		autoindex on;
		# expires 1d;
	}

	location /static {
		alias /var/www/html/staticfiles;
		autoindex on;
		# expires 1d;
	}

	location /js {
		alias /var/www/html/staticfiles/js;
		autoindex on;
	}

	# Temp? rule to prevent django's 404 page from appearing on static assets
	# Firefox freaks out when its expecting a .js file and it gets a django's html instead
	location /widget/ {
		try_files $uri =404;
	}
}
