# Generated by Django 5.0.1 on 2025-04-21 16:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(db_collation='utf8_bin', max_length=10, primary_key=True, serialize=False)),
                ('file_type', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(default='', max_length=300)),
                ('file_size', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('start_at', models.DateTimeField(default=datetime.datetime.now)),
                ('end_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'date_range',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('play_id', models.CharField(db_collation='utf8_bin', max_length=100)),
                ('log_type', models.CharField(blank=True, choices=[('', 'Empty'), ('BUTTON_PRESS', 'Button Press'), ('ERROR_GENERAL', 'General Error'), ('ERROR_TIME_VALIDATION', 'Time Validation Error'), ('KEY_PRESS', 'Key Press'), ('SCORE_ACTIVITY_FROM_CLIENT', 'Client Score Activity'), ('SCORE_FINAL_FROM_CLIENT', 'Final Client Score'), ('SCORE_QUESTION_ANSWERED', 'Question Answered'), ('SCORE_WIDGET_INTERACTION', 'Widget Score Interaction'), ('SCORE_PARTICIPATION', 'Participation Score'), ('WIDGET_CORE_INIT', 'Widget Initialization'), ('WIDGET_END', 'Widget End'), ('WIDGET_LOAD_DONE', 'Finish Widget Load'), ('WIDGET_LOAD_START', 'Start Widget Load'), ('WIDGET_LOGIN', 'Widget Login'), ('WIDGET_PLAY_REQ', 'Widget Play Request'), ('WIDGET_PLAY_START', 'Widget Play Start'), ('WIDGET_RESTART', 'Widget Restart'), ('WIDGET_START', 'Widget Start'), ('WIDGET_STATE', 'Widget State'), ('DATA', 'Data')], default='', max_length=26, null=True)),
                ('item_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('game_time', models.IntegerField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='LogActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('item_id', models.CharField(db_collation='utf8_bin', max_length=100)),
                ('value_1', models.CharField(blank=True, max_length=255, null=True)),
                ('value_2', models.CharField(blank=True, max_length=255, null=True)),
                ('value_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'log_activity',
            },
        ),
        migrations.CreateModel(
            name='LogPlay',
            fields=[
                ('id', models.CharField(db_collation='utf8_bin', max_length=100, primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.CharField(max_length=20)),
                ('is_complete', models.BooleanField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=52)),
                ('score_possible', models.IntegerField()),
                ('percent', models.FloatField()),
                ('elapsed', models.IntegerField()),
                ('environment_data', models.TextField()),
                ('auth', models.CharField(choices=[('', ''), ('lti', 'lti')], max_length=3)),
                ('referrer_url', models.CharField(max_length=255)),
                ('context_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'log_play',
            },
        ),
        migrations.CreateModel(
            name='LogStorage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=64)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'log_storage',
            },
        ),
        migrations.CreateModel(
            name='Lti',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_link', models.CharField(max_length=255)),
                ('consumer', models.CharField(max_length=255)),
                ('consumer_guid', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('context_id', models.CharField(blank=True, max_length=255, null=True)),
                ('context_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'lti',
            },
        ),
        migrations.CreateModel(
            name='MapAssetToObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_collation='utf8_bin', max_length=255)),
                ('object_type', models.IntegerField()),
                ('asset_id', models.CharField(db_collation='utf8_bin', max_length=10)),
            ],
            options={
                'db_table': 'map_asset_to_object',
            },
        ),
        migrations.CreateModel(
            name='MapQuestionToQset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'map_question_to_qset',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.IntegerField(null=True)),
                ('item_id', models.CharField(db_collation='utf8_bin', max_length=100)),
                ('is_email_sent', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('subject', models.CharField(max_length=511)),
                ('avatar', models.CharField(max_length=511)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='PermObjectToUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_collation='utf8_bin', max_length=10)),
                ('perm', models.IntegerField(choices=[(1, 'Can see object and view scores'), (30, 'Full access to object')])),
                ('object_type', models.IntegerField(choices=[(1, 'Question'), (2, 'Media asset'), (3, 'Widget engine'), (4, 'Widget instance')])),
                ('expires_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'perm_object_to_user',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('questions_list', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='UserExtraAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.CharField(db_collation='utf8_bin', max_length=100)),
                ('user_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('extra_attempts', models.IntegerField()),
                ('context_id', models.CharField(max_length=255)),
                ('semester', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'user_extra_attempts',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('flash_version', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('is_scalable', models.BooleanField(default=True)),
                ('score_module', models.CharField(default='base', max_length=100)),
                ('score_type', models.CharField(choices=[('SERVER', 'widget is scored on the server'), ('CLIENT', 'widget is scored on the client'), ('SERVER-CLIENT', 'widget is partially scored in both server and client')], default='SERVER', max_length=13)),
                ('is_qset_encrypted', models.BooleanField(default=True)),
                ('is_answer_encrypted', models.BooleanField(default=True)),
                ('is_storage_enabled', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_playable', models.BooleanField(default=True)),
                ('is_scorable', models.BooleanField(default=True)),
                ('in_catalog', models.BooleanField(default=True)),
                ('is_generable', models.BooleanField(default=False)),
                ('uses_prompt_generation', models.BooleanField(default=False)),
                ('creator', models.CharField(default='', max_length=255)),
                ('clean_name', models.CharField(default='', max_length=255)),
                ('player', models.CharField(default='', max_length=255)),
                ('api_version', models.IntegerField(default=0)),
                ('package_hash', models.CharField(db_collation='utf8_bin', default='', max_length=32)),
                ('score_screen', models.CharField(default='', max_length=255)),
                ('restrict_publish', models.BooleanField(default=False)),
                ('creator_guide', models.CharField(default='', max_length=255)),
                ('player_guide', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'widget',
            },
        ),
        migrations.CreateModel(
            name='WidgetInstance',
            fields=[
                ('id', models.CharField(db_collation='utf8_bin', max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('is_draft', models.BooleanField(default=False)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('open_at', models.DateTimeField(default=None, null=True)),
                ('close_at', models.DateTimeField(default=None, null=True)),
                ('attempts', models.IntegerField(default=-1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guest_access', models.BooleanField(default=False)),
                ('is_student_made', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('embedded_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'widget_instance',
            },
        ),
        migrations.CreateModel(
            name='WidgetMetadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'widget_metadata',
            },
        ),
        migrations.CreateModel(
            name='WidgetQset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('data', models.TextField(db_column='data')),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'widget_qset',
            },
        ),
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.CharField(db_collation='utf8_bin', max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('bytes', models.IntegerField()),
                ('hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'asset_data',
                'indexes': [models.Index(fields=['hash'], name='asset_data_hash'), models.Index(fields=['created_at'], name='asset_data_created_at')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetdata',
            constraint=models.UniqueConstraint(fields=('id', 'size'), name='asset_data_main'),
        ),
        migrations.AddConstraint(
            model_name='daterange',
            constraint=models.UniqueConstraint(fields=('semester', 'year', 'start_at', 'end_at'), name='date_range_main'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['play_id'], name='log_play_id'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['log_type'], name='log_type'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['created_at'], name='log_created_at'),
        ),
        migrations.AddField(
            model_name='logactivity',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logplay',
            name='semester',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.PROTECT, related_name='play_logs', to='core.daterange'),
        ),
        migrations.AddField(
            model_name='logplay',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logstorage',
            name='play_log',
            field=models.ForeignKey(db_column='play_id', on_delete=django.db.models.deletion.PROTECT, related_name='storage_logs', to='core.logplay'),
        ),
        migrations.AddField(
            model_name='logstorage',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lti',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lti_embeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mapassettoobject',
            constraint=models.UniqueConstraint(fields=('object_id', 'object_type', 'asset_id'), name='map_asset_to_object_main'),
        ),
        migrations.AddField(
            model_name='notification',
            name='from_id',
            field=models.ForeignKey(blank=True, db_column='from_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_id',
            field=models.ForeignKey(blank=True, db_column='to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permobjecttouser',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapquestiontoqset',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, to='core.question'),
        ),
        migrations.AddIndex(
            model_name='userextraattempts',
            index=models.Index(fields=['user_id'], name='user_extra_attempts_user_id'),
        ),
        migrations.AddIndex(
            model_name='userextraattempts',
            index=models.Index(fields=['inst_id'], name='user_extra_attempts_inst_id'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['clean_name'], name='widget_clean_name'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['in_catalog'], name='widget_in_catalog'),
        ),
        migrations.AddField(
            model_name='widgetinstance',
            name='published_by',
            field=models.ForeignKey(blank=True, db_column='published_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widgetinstance',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widgetinstance',
            name='widget',
            field=models.ForeignKey(db_column='widget_id', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.widget'),
        ),
        migrations.AddField(
            model_name='lti',
            name='widget_instance',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='lti_embeds', to='core.widgetinstance'),
        ),
        migrations.AddField(
            model_name='logstorage',
            name='instance',
            field=models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.PROTECT, related_name='storage_logs', to='core.widgetinstance'),
        ),
        migrations.AddField(
            model_name='logplay',
            name='instance',
            field=models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.PROTECT, related_name='play_logs', to='core.widgetinstance'),
        ),
        migrations.AddField(
            model_name='widgetmetadata',
            name='widget',
            field=models.ForeignKey(db_column='widget_id', on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='core.widget'),
        ),
        migrations.AddField(
            model_name='widgetqset',
            name='instance',
            field=models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.PROTECT, related_name='qsets', to='core.widgetinstance'),
        ),
        migrations.AddField(
            model_name='question',
            name='qset',
            field=models.ForeignKey(blank=True, db_column='qset_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flattened_questions', to='core.widgetqset'),
        ),
        migrations.AddField(
            model_name='mapquestiontoqset',
            name='qset',
            field=models.ForeignKey(db_column='qset_id', on_delete=django.db.models.deletion.PROTECT, to='core.widgetqset'),
        ),
        migrations.AddField(
            model_name='logplay',
            name='qset',
            field=models.ForeignKey(db_column='qset_id', on_delete=django.db.models.deletion.PROTECT, related_name='play_logs', to='core.widgetqset'),
        ),
        migrations.AddIndex(
            model_name='logactivity',
            index=models.Index(fields=['type'], name='log_activity_type'),
        ),
        migrations.AddIndex(
            model_name='logactivity',
            index=models.Index(fields=['item_id'], name='log_activity_item_id'),
        ),
        migrations.AddIndex(
            model_name='logactivity',
            index=models.Index(fields=['created_at'], name='log_activity_created_at'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_email_sent'], name='notification_is_email_sent'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['to_id'], name='notification_to_id'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['from_id'], name='notification_from_id'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['item_type'], name='notification_item_type'),
        ),
        migrations.AddConstraint(
            model_name='permobjecttouser',
            constraint=models.UniqueConstraint(fields=('object_id', 'user_id', 'perm', 'object_type'), name='perm_object_to_user_main'),
        ),
        migrations.AddIndex(
            model_name='widgetinstance',
            index=models.Index(fields=['created_at'], name='widget_instance_created_at'),
        ),
        migrations.AddIndex(
            model_name='widgetinstance',
            index=models.Index(fields=['is_draft'], name='widget_instance_is_draft'),
        ),
        migrations.AddIndex(
            model_name='widgetinstance',
            index=models.Index(fields=['is_deleted'], name='widget_instance_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='lti',
            index=models.Index(fields=['resource_link'], name='lti_resource_link'),
        ),
        migrations.AddIndex(
            model_name='lti',
            index=models.Index(fields=['consumer_guid'], name='lti_consumer_guid'),
        ),
        migrations.AddIndex(
            model_name='logstorage',
            index=models.Index(fields=['created_at'], name='log_storage_created_at'),
        ),
        migrations.AddIndex(
            model_name='logstorage',
            index=models.Index(fields=['name'], name='log_storage_name'),
        ),
        migrations.AddIndex(
            model_name='widgetqset',
            index=models.Index(fields=['created_at'], name='widget_qset_created_at'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['qset'], name='question_qset_idx'),
        ),
        migrations.AddIndex(
            model_name='logplay',
            index=models.Index(fields=['created_at'], name='log_play_created_at'),
        ),
        migrations.AddIndex(
            model_name='logplay',
            index=models.Index(fields=['is_complete'], name='log_play_is_complete'),
        ),
        migrations.AddIndex(
            model_name='logplay',
            index=models.Index(fields=['percent'], name='log_play_percent'),
        ),
    ]
