# Generated by Django 5.0.1 on 2024-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_id_logactivity_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(blank=True, choices=[('BUTTON_PRESS', 'BUTTON_PRESS'), ('ERROR_GENERAL', 'ERROR_GENERAL'), ('ERROR_TIME_VALIDATION', 'ERROR_TIME_VALIDATION'), ('KEY_PRESS', 'KEY_PRESS'), ('SCORE_ACTIVITY_FROM_CLIENT', 'SCORE_ACTIVITY_FROM_CLIENT'), ('SCORE_FINAL_FROM_CLIENT', 'SCORE_FINAL_FROM_CLIENT'), ('SCORE_QUESTION_ANSWERED', 'SCORE_QUESTION_ANSWERED'), ('SCORE_WIDGET_INTERACTION', 'SCORE_WIDGET_INTERACTION'), ('SCORE_PARTICIPATION', 'SCORE_PARTICIPATION'), ('WIDGET_CORE_INIT', 'WIDGET_CORE_INIT'), ('WIDGET_END', 'WIDGET_END'), ('WIDGET_LOAD_DONE', 'WIDGET_LOAD_DONE'), ('WIDGET_LOAD_START', 'WIDGET_LOAD_START'), ('WIDGET_LOGIN', 'WIDGET_LOGIN'), ('WIDGET_PLAY_REQ', 'WIDGET_PLAY_REQ'), ('WIDGET_PLAY_START', 'WIDGET_PLAY_START'), ('WIDGET_RESTART', 'WIDGET_RESTART'), ('WIDGET_START', 'WIDGET_START'), ('WIDGET_STATE', 'WIDGET_STATE'), ('DATA', 'DATA')], max_length=26, null=True),
        ),
    ]
