# Generated by Django 5.0.1 on 2024-05-23 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_user_id_logactivity_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="log",
            name="log_type",
        ),
        migrations.RenameField(model_name="log", old_name="type", new_name="log_type"),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["log_type"], name="log_type"),
        ),
    ]
