# Generated by Django 5.0.1 on 2024-05-17 18:27

from datetime import datetime

from django.db import migrations, models
from django.utils import timezone


def translate_timestamps(apps, schema_editor):
    import logging

    logger = logging.getLogger("django")

    def timestamp_to_datetime(ts):
        if ts is None:
            return None
        from django.utils.timezone import make_aware

        return make_aware(datetime.fromtimestamp(ts))

    logger.info("Converting Asset timestamps to datetimes")
    Asset = apps.get_model("core", "Asset")
    for asset in Asset.objects.all():
        asset.created_at_dt = timestamp_to_datetime(asset.created_at)
        asset.deleted_at_dt = timestamp_to_datetime(asset.deleted_at)
        asset.save()

    logger.info("Converting AssetData timestamps to datetimes")
    AssetData = apps.get_model("core", "AssetData")
    for asset_data in AssetData.objects.all():
        asset_data.created_at_dt = timestamp_to_datetime(asset_data.created_at)
        asset_data.save()

    logger.info("Converting DateRange timestamps to datetimes")
    DateRange = apps.get_model("core", "DateRange")
    for date_range in DateRange.objects.all():
        date_range.start_at_dt = timestamp_to_datetime(date_range.start_at)
        date_range.end_at_dt = timestamp_to_datetime(date_range.end_at)
        date_range.save()

    logger.info("Converting Log timestamps to datetimes")
    Log = apps.get_model("core", "Log")
    for log in Log.objects.all():
        log.created_at_dt = timestamp_to_datetime(log.created_at)
        log.save()

    logger.info("Converting LogActivity timestamps to datetimes")
    LogActivity = apps.get_model("core", "LogActivity")
    for log_activity in LogActivity.objects.all():
        log_activity.created_at_dt = timestamp_to_datetime(log_activity.created_at)
        log_activity.save()

    logger.info("Converting LogPlay timestamps to datetimes")
    LogPlay = apps.get_model("core", "LogPlay")
    for log_play in LogPlay.objects.all():
        log_play.created_at_dt = timestamp_to_datetime(log_play.created_at)
        log_play.save()

    logger.info("Converting LogStorage timestamps to datetimes")
    LogStorage = apps.get_model("core", "LogStorage")
    for log_storage in LogStorage.objects.all():
        log_storage.created_at_dt = timestamp_to_datetime(log_storage.created_at)
        log_storage.save()

    logger.info("Converting Lti timestamps to datetimes")
    Lti = apps.get_model("core", "Lti")
    for lti in Lti.objects.all():
        lti.created_at_dt = timestamp_to_datetime(lti.created_at)
        lti.updated_at_dt = timestamp_to_datetime(lti.updated_at)
        lti.save()

    logger.info("Converting Notification timestamps to datetimes")
    Notification = apps.get_model("core", "Notification")
    for notification in Notification.objects.all():
        notification.created_at_dt = timestamp_to_datetime(notification.created_at)
        notification.updated_at_dt = timestamp_to_datetime(notification.updated_at)
        notification.save()

    logger.info("Converting PermObjectToUser timestamps to datetimes")
    PermObjectToUser = apps.get_model("core", "PermObjectToUser")
    for potu in PermObjectToUser.objects.all():
        potu.expires_at_dt = timestamp_to_datetime(potu.expires_at)
        potu.save()

    logger.info("Converting UserExtraAttempts timestamps to datetimes")
    UserExtraAttempts = apps.get_model("core", "UserExtraAttempts")
    for uea in UserExtraAttempts.objects.all():
        uea.created_at_dt = timestamp_to_datetime(uea.created_at)
        uea.save()

    logger.info("Converting Question timestamps to datetimes")
    Question = apps.get_model("core", "Question")
    for question in Question.objects.all():
        question.created_at_dt = timestamp_to_datetime(question.created_at)
        question.save()

    logger.info("Converting Widget timestamps to datetimes")
    Widget = apps.get_model("core", "Widget")
    for widget in Widget.objects.all():
        widget.created_at_dt = timestamp_to_datetime(widget.created_at)
        widget.save()

    logger.info("Converting WidgetInstance timestamps to datetimes")
    WidgetInstance = apps.get_model("core", "WidgetInstance")
    for wi in WidgetInstance.objects.all():
        wi.created_at_dt = timestamp_to_datetime(wi.created_at)
        wi.save()

    logger.info("Converting WidgetQset timestamps to datetimes")
    WidgetQset = apps.get_model("core", "WidgetQset")
    for wq in WidgetQset.objects.all():
        wq.created_at_dt = timestamp_to_datetime(wq.created_at)
        wq.save()


def translate_datetimes(apps, schema_editor):
    import logging

    logger = logging.getLogger("django")

    def datetime_to_timestamp(dt):
        if dt is None:
            return None
        from datetime import datetime

        return datetime.timestamp(dt)

    logger.info("Converting Asset datetimes to timestamps")
    Asset = apps.get_model("core", "Asset")
    for asset in Asset.objects.all():
        asset.created_at = datetime_to_timestamp(asset.created_at_dt)
        asset.deleted_at = datetime_to_timestamp(asset.deleted_at_dt)
        asset.save()

    logger.info("Converting AssetData datetimes to timestamps")
    AssetData = apps.get_model("core", "AssetData")
    for asset_data in AssetData.objects.all():
        asset_data.created_at = datetime_to_timestamp(asset_data.created_at_dt)
        asset_data.save()

    logger.info("Converting DateRange datetimes to timestamps")
    DateRange = apps.get_model("core", "DateRange")
    for date_range in DateRange.objects.all():
        date_range.start_at = datetime_to_timestamp(date_range.start_at_dt)
        date_range.end_at = datetime_to_timestamp(date_range.end_at_dt)
        date_range.save()

    logger.info("Converting Log datetimes to timestamps")
    Log = apps.get_model("core", "Log")
    for log in Log.objects.all():
        log.created_at = datetime_to_timestamp(log.created_at_dt)
        log.save()

    logger.info("Converting LogActivity datetimes to timestamps")
    LogActivity = apps.get_model("core", "LogActivity")
    for log_activity in LogActivity.objects.all():
        log_activity.created_at = datetime_to_timestamp(log_activity.created_at_dt)
        log_activity.save()

    logger.info("Converting LogPlay datetimes to timestamps")
    LogPlay = apps.get_model("core", "LogPlay")
    for log_play in LogPlay.objects.all():
        log_play.created_at = datetime_to_timestamp(log_play.created_at_dt)
        log_play.save()

    logger.info("Converting LogStorage datetimes to timestamps")
    LogStorage = apps.get_model("core", "LogStorage")
    for log_storage in LogStorage.objects.all():
        log_storage.created_at = datetime_to_timestamp(log_storage.created_at_dt)
        log_storage.save()

    logger.info("Converting Lti datetimes to timestamps")
    Lti = apps.get_model("core", "Lti")
    for lti in Lti.objects.all():
        lti.created_at = datetime_to_timestamp(lti.created_at_dt)
        lti.updated_at = datetime_to_timestamp(lti.updated_at_dt)
        lti.save()

    logger.info("Converting Notification datetimes to timestamps")
    Notification = apps.get_model("core", "Notification")
    for notification in Notification.objects.all():
        notification.created_at = datetime_to_timestamp(notification.created_at_dt)
        notification.updated_at = datetime_to_timestamp(notification.updated_at_dt)
        notification.save()

    logger.info("Converting PermObjectToUser datetimes to timestamps")
    PermObjectToUser = apps.get_model("core", "PermObjectToUser")
    for potu in PermObjectToUser.objects.all():
        potu.expires_at = datetime_to_timestamp(potu.expires_at_dt)
        potu.save()

    logger.info("Converting UserExtraAttempts datetimes to timestamps")
    UserExtraAttempts = apps.get_model("core", "UserExtraAttempts")
    for uea in UserExtraAttempts.objects.all():
        uea.created_at = datetime_to_timestamp(uea.created_at_dt)
        uea.save()

    logger.info("Converting Question datetimes to timestamps")
    Question = apps.get_model("core", "Question")
    for question in Question.objects.all():
        question.created_at = datetime_to_timestamp(question.created_at_dt)
        question.save()

    logger.info("Converting Widget datetimes to timestamps")
    Widget = apps.get_model("core", "Widget")
    for widget in Widget.objects.all():
        widget.created_at = datetime_to_timestamp(widget.created_at_dt)
        widget.save()

    logger.info("Converting WidgetInstance datetimes to timestamps")
    WidgetInstance = apps.get_model("core", "WidgetInstance")
    for wi in WidgetInstance.objects.all():
        wi.created_at = datetime_to_timestamp(wi.created_at_dt)
        wi.save()

    logger.info("Converting WidgetQset datetimes to timestamps")
    WidgetQset = apps.get_model("core", "WidgetQset")
    for wq in WidgetQset.objects.all():
        wq.created_at = datetime_to_timestamp(wq.created_at_dt)
        wq.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_log_log_type_alter_logactivity_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="updated_at_dt",
            field=models.DateTimeField(default=timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="permobjecttouser",
            name="expires_at_dt",
            field=models.DateTimeField(default=timezone.now, null=True),
        ),
        migrations.RunPython(translate_timestamps, translate_datetimes),
    ]
