# Generated by Django 5.0.1 on 2024-06-17 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_convert_timestamps_to_datetimes'),
    ]

    operations = [
        # we can't remove these columns while the constraint is in place, so we have to temporarily remove it
        # this constraint will be re-added as the last operation of this migration
        migrations.RemoveConstraint(
            model_name="daterange",
            name="date_range_main"
        ),

        migrations.RemoveField(
            model_name='daterange',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='daterange',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='logactivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='logplay',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='logstorage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lti',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lti',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='permobjecttouser',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),

        migrations.RenameField(
            model_name='daterange',
            old_name='end_at_dt',
            new_name='end_at'
        ),
        migrations.RenameField(
            model_name='daterange',
            old_name='start_at_dt',
            new_name='start_at'
        ),
        migrations.RenameField(
            model_name='log',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.RenameField(
            model_name='logactivity',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.RenameField(
            model_name='logplay',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.RenameField(
            model_name='logstorage',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.RenameField(
            model_name='lti',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.RenameField(
            model_name='lti',
            old_name='updated_at_dt',
            new_name='updated_at'
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='updated_at_dt',
            new_name='updated_at'
        ),
        migrations.RenameField(
            model_name='permobjecttouser',
            old_name='expires_at_dt',
            new_name='expires_at'
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_at_dt',
            new_name='created_at'
        ),
        migrations.AddConstraint(
            model_name="daterange",
            constraint=models.UniqueConstraint(
                fields=("semester", "year", "start_at", "end_at"),
                name="date_range_main",
            ),
        ),
    ]
