# Generated by Django 5.0.1 on 2024-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_daterange_end_at_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='widget',
            name='api_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='widget',
            name='clean_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='creator',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='creator_guide',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='flash_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='widget',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='widget',
            name='in_catalog',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_answer_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_playable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_qset_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_scalable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_scorable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='is_storage_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='package_hash',
            field=models.CharField(db_collation='utf8_bin', default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='widget',
            name='player',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='player_guide',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='restrict_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='score_module',
            field=models.CharField(default='base', max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='score_screen',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='score_type',
            field=models.CharField(choices=[('SERVER', 'widget is scored on the server'), ('CLIENT', 'widget is scored on the client'), ('SERVER-CLIENT', 'widget is partially scored in both server and client')], default='SERVER', max_length=13),
        ),
        migrations.AlterField(
            model_name='widget',
            name='width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
