# Generated by Django 5.0.1 on 2025-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="logplay",
            name="lti_token",
            field=models.CharField(default="", max_length=100),
        ),
    ]
