# Generated by Django 5.0.1 on 2025-03-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_widgetinstance_close_at_and_more'),
        ('core', '0015_remove_usersettings_settings_and_more'),
    ]

    operations = [
    ]
