# Generated by Django 5.0.1 on 2025-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_widgetinstance_close_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="data",
            field=models.TextField(blank=True, db_column="data", null=True),
        ),
        migrations.RenameField(
            model_name="question",
            old_name="data",
            new_name="_data",
        ),
    ]
