# Generated by Django 5.0.1 on 2025-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_question_data_rename_data_question__data'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetqset',
            name='questions_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
