# Generated by Django 5.0.1 on 2025-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_widgetqset_questions_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetqset',
            name='questions_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
