# Generated by Django 5.0.1 on 2025-04-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_migrate_permobjecttouser_to_objectpermissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetdata",
            old_name="type",
            new_name="file_type",
        ),
    ]
