# Generated by Django 5.0.1 on 2025-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rename_type_assetdata_file_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="question_hash",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="question",
            name="_data",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="data",
        ),
        migrations.RemoveField(
            model_name="question",
            name="hash",
        ),
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="qset",
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(default="QA", max_length=50),
        ),
    ]
