# Generated by Django 5.0.1 on 2025-05-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rename_type_assetdata_file_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="question_hash",
        ),
        migrations.RemoveIndex(
            model_name="question",
            name="question_type",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="questions_list",
        ),
        migrations.RemoveField(
            model_name="question",
            name="_data",
        ),
        migrations.RemoveField(
            model_name="question",
            name="hash",
        ),
        migrations.RemoveField(
            model_name="question",
            name="type",
        ),
        migrations.RemoveField(
            model_name="question",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="qset",
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["qset"], name="question_qset_idx"),
        ),
        migrations.AddField(
            model_name="question",
            name="qset",
            field=models.ForeignKey(
                blank=True,
                db_column="qset_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flattened_questions",
                to="core.widgetqset",
            ),
        ),
    ]
