# Generated by Django 5.0.1 on 2025-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_type_assetdata_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='update_method',
            field=models.CharField(choices=[('github', 'Update via a Github releases API URL')], default=None, max_length=255, null=True),  # noqa: E501
        ),
        migrations.AddField(
            model_name='widget',
            name='update_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
