# Generated by Django 5.0.1 on 2025-10-06 17:52

from django.db import migrations


def create_perm_tables_if_deleted(apps, schema_editor):
    all_tables = schema_editor.connection.introspection.table_names()
    if "perm_role_to_user" not in all_tables:
        schema_editor.execute("CREATE TABLE perm_role_to_user (temp_col int null);")


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0022_fix_logstorage_data"),
    ]

    operations = [
        migrations.RunPython(create_perm_tables_if_deleted, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="PermRoleToUser",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.DeleteModel(
            name="PermObjectToUser",
        ),
    ]
