"""
This migration no longer does what the name suggests. It has been decided that the old question model
is getting nuked, so this migration has been modified to achieve that. File name has been kept the same
since Django will notice and throw an error otherwise.
"""

# Generated by Django 5.0.1 on 2025-08-07 17:05

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_question_question_hash_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="question",
            new_name="question_old",
        ),
        migrations.AlterModelTable(
            name="question_old",
            table="question_old",
        ),
        migrations.AlterModelOptions(
            name="question_old",
            options={"managed": False},
        ),
        migrations.DeleteModel(
            name="question_old",
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "qset",
                    models.ForeignKey(
                        db_column="qset_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="core.widgetqset",
                    ),
                ),
                ("_data", models.TextField(db_column="data")),
                ("item_id", models.CharField(max_length=100, blank=True)),
                ("created_at", models.DateTimeField(default=timezone.now)),
                (
                    "type",
                    models.ForeignKey(
                        db_column="type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="widget_type",
                        to="core.widget",
                    ),
                ),
            ],
            options={
                "db_table": "question",
            },
        ),
    ]
