# Generated by Django 5.0.1 on 2025-05-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_question_question_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="qset",
            field=models.ForeignKey(
                to="core.widgetqset",
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
                related_name="flattened_questions",
                db_column="qset_id",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["qset"], name="question_qset_idx"),
        ),
    ]
