# Generated by Django 5.0.1 on 2025-08-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_question_question_hash_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="question",
            name="question_qset_idx",
        ),
        migrations.AlterField(
            model_name="question",
            name="qset",
            field=models.ForeignKey(
                db_column="qset_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="core.widgetqset",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.ForeignKey(
                db_column="type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="widget_type",
                to="core.widget",
            ),
        ),
    ]
