"""
Like the last migration, this migration no longer does what the name suggests. The old question model
no longer exists, so this migration serves no purpose. File name has been kept the same since Django
will notice and throw an error otherwise.
"""

# Generated by Django 5.0.1 on 2025-08-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_question_question_qset_idx_and_more"),
    ]

    operations = []
