# Generated by Django 5.0.1 on 2025-05-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_readd_qset_to_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="questions_list",
            new_name="data",
        ),
    ]
