# Generated by Django 5.0.1 on 2025-08-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_deprecate_old_question_model_and_make_new"),
    ]

    operations = []
