# Generated by Django 5.0.1 on 2025-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_question_question_qset_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="data",
            field=models.TextField(db_column="data"),
        ),
        migrations.RenameField(
            model_name="question",
            old_name="data",
            new_name="_data",
        ),
        migrations.AddField(
            model_name="question",
            name="item_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
