# Generated by Django 5.0.1 on 2025-08-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_question_data_rename_data_question__data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logplay",
            name="environment_data",
        ),
        migrations.AddField(
            model_name="logplay",
            name="lti_token",
            field=models.CharField(default="", max_length=100),
        ),
    ]
