# Generated by Django 5.0.1 on 2025-08-20 21:32

from django.db import migrations, models


class WidgetMetadataInMigration(models.Model):
    id = models.BigAutoField(primary_key=True)
    widget = models.ForeignKey(
        "Widget",
        related_name="metadata",
        on_delete=models.PROTECT,
        db_column="widget_id",
    )
    name = models.CharField(max_length=255)
    value = models.TextField()

    class Meta:
        db_table = "widget_metadata"
        managed = False


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_alter_question_data_rename_data_question__data_and_more'),
    ]

    def convert_table_to_json(apps, schema_editor):
        widget_metadata_json = {}
        for metadata_row in WidgetMetadataInMigration.objects.all():
            if metadata_row.widget.id not in widget_metadata_json:
                widget_metadata_json[metadata_row.widget.id] = {}
            widget_metadata_json[metadata_row.widget.id][metadata_row.name] = metadata_row.value
        pass

    def convert_json_to_table(apps, schema_editor):

        pass

    operations = [
        migrations.AddField(
            model_name='widget',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        # migrations.RunPython(convert_table_to_json, convert_json_to_table),
        migrations.DeleteModel(
            name='WidgetMetadata',
        ),
    ]
