# Generated by Django 5.0.1 on 2025-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_lti_deployment_lti_lti_version_alter_lti_consumer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectpermission",
            name="context_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="objectpermission",
            unique_together={("user", "content_type", "object_id", "context_id")},
        ),
    ]
