# Generated by Django 5.0.1 on 2026-01-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_objectpermission_context_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LtiPlayState",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ags_line_item",
                    models.CharField(db_collation="utf8_bin", max_length=255),
                ),
                (
                    "ags_user_id",
                    models.CharField(db_collation="utf8_bin", max_length=255),
                ),
                ("ags_scoring_enabled", models.BooleanField(default=True)),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not Submitted"),
                            ("SUCCESS", "Success"),
                            ("AGS_NOT_INCLUDED", "AGS Not Included"),
                            ("NOT_GRADED", "Not Graded"),
                            ("ERR_NO_ATTEMPTS", "No Attempts"),
                            ("ERR_FAILURE", "Failure"),
                        ],
                        default="NOT_SUBMITTED",
                        max_length=26,
                    ),
                ),
                ("submission_attempts", models.PositiveIntegerField(default=0)),
                ("last_submitted", models.DateTimeField(default=None, null=True)),
                (
                    "lti_association",
                    models.ForeignKey(
                        db_column="lti_assoc",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lti_association",
                        to="core.lti",
                    ),
                ),
                (
                    "play",
                    models.OneToOneField(
                        db_column="play_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lti_play_state",
                        to="core.logplay",
                    ),
                ),
            ],
        ),
    ]
