# Generated by Django 5.0.1 on 2025-09-15 17:33
# TODO: When Materia Django is finished, REMOVE this migration.
#       It was used to get dev databases to match the latest PHP
#       changes DB (the featured flag). If the featured flag already
#       exists, this migration won't do anything. Reversing this
#       migration will also keep the featured flag intact.

from django.db import migrations


def add_featured_flag(apps, schema_editor):
    Widget = apps.get_model("core", "Widget")
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Check to see if featured flag already exists
        cursor.execute("DESCRIBE widget;")
        rows = cursor.fetchall()
        for row in rows:
            column_name = row[0]
            if column_name == "featured":
                return  # Featured flag found, skip this entire migration

        # Add featured field
        cursor.execute("ALTER TABLE widget ADD COLUMN featured boolean DEFAULT FALSE;")

    # Migrate data over to featured
    for widget in Widget.objects.using(db_alias).all():
        widget.featured = 1 if widget.in_catalog else 0
        widget.in_catalog = (
            widget.is_playable
        )  # widgets used to only show in the catalog if they were playable
        widget.save()


def remove_featured_flag(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_logplay_environment_data_logplay_lti_token"),
    ]

    operations = [
        migrations.RunPython(add_featured_flag, remove_featured_flag),
    ]
