# Generated by Django 5.0.1 on 2025-08-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_noop"),
        ("core", "0025_remove_logplay_environment_data_logplay_lti_token"),
    ]

    operations = []
