# Generated by Django 5.0.1 on 2025-12-11 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_objectpermission_context_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="logplay",
            index=models.Index(fields=["user"], name="log_play_user"),
        ),
        migrations.AddIndex(
            model_name="logplay",
            index=models.Index(fields=["instance"], name="log_play_instance"),
        ),
    ]
