# Generated by Django 5.0.1 on 2025-08-20 21:32

from django.db import migrations, models

from core.models import Widget


def convert_table_to_json(apps, schema_editor):
    WidgetMetadata = apps.get_model("core", "WidgetMetadata")
    db_alias = schema_editor.connection.alias

    # Compile all metadata from widget_metadata as JSON
    list_fields = ["features", "supported_data", "playdata_exporters"]
    widget_metadata_json = {}
    for metadata_row in WidgetMetadata.objects.using(db_alias).all():
        widget_id = metadata_row.widget_id
        field_name = metadata_row.name
        value = metadata_row.value

        # Check if widget entry exists
        if widget_id not in widget_metadata_json:
            widget_metadata_json[widget_id] = {}

        # Check if this field is supposed to be in a list
        if field_name in list_fields:
            if field_name not in widget_metadata_json[widget_id]:
                widget_metadata_json[widget_id][field_name] = []
            widget_metadata_json[widget_id][field_name].append(value)
            continue

        # Otherwise, just put it in the JSON as is
        widget_metadata_json[widget_id][field_name] = value

    # Save each widget's metadata
    for widget_id, metadata in widget_metadata_json.items():
        widget = Widget.objects.get(id=widget_id)
        widget.metadata = metadata
        widget.save()


def convert_json_to_table(apps, schema_editor):
    WidgetMetadata = apps.get_model("core", "WidgetMetadata")
    db_alias = schema_editor.connection.alias

    for widget in Widget.objects.all():
        for field_name, value in widget.metadata.items():
            # If value is a list, create multiple WidgetMetadata instances
            if isinstance(value, list):
                for item in value:
                    WidgetMetadata.objects.using(db_alias).create(
                        widget_id=widget.id,
                        name=field_name,
                        value=item,
                    )
            # Otherwise, just put it as a single entry
            else:
                WidgetMetadata.objects.using(db_alias).create(
                    widget_id=widget.id,
                    name=field_name,
                    value=value,
                )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_widget_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(convert_table_to_json, convert_json_to_table),
        migrations.DeleteModel(
            name="WidgetMetadata",
        ),
    ]
