# Generated by Django 5.0.1 on 2026-03-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_ltiplaystate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ltiplaystate",
            name="score_submitted",
            field=models.FloatField(null=True),
        ),
    ]
