# Generated by Django 5.0.1 on 2025-09-15 17:33

from django.db import migrations, models


def add_featured_flag(apps, schema_editor):
    Widget = apps.get_model("core", "Widget")
    db_alias = schema_editor.connection.alias
    for widget in Widget.objects.using(db_alias).all():
        widget.featured = widget.in_catalog
        widget.in_catalog = (
            widget.is_playable
        )  # widgets used to only show in the catalog if they were playable
        widget.save()


def remove_featured_flag(apps, schema_editor):
    Widget = apps.get_model("core", "Widget")
    db_alias = schema_editor.connection.alias
    for widget in Widget.objects.using(db_alias).all():
        widget.in_catalog = widget.featured
        widget.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_merge_20250819_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_featured_flag, remove_featured_flag),
    ]
