# Generated by Django 5.0.1 on 2025-09-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_merge_20250819_1026"),
        ("lti_tool", "0006_ltiregistration_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lti",
            name="deployment",
            field=models.ForeignKey(
                blank=True,
                db_column="deployment_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployment",
                to="lti_tool.ltideployment",
            ),
        ),
        migrations.AddField(
            model_name="lti",
            name="lti_version",
            field=models.CharField(
                choices=[("1.1", "LTI 1.1"), ("1.3", "LTI 1.3")],
                default="1.1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lti",
            name="consumer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lti",
            name="consumer_guid",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="lti",
            index=models.Index(fields=["deployment"], name="lti_deployment"),
        ),
    ]
