# Generated by Django 5.0.1 on 2025-09-15 21:28
import django
from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models

from core.models import WidgetInstance


def clean_data(apps, schema_editor):
    """
    Deletes UserExtraAttempts that do not have a valid user_id or inst_id
    """
    print()  # print newline because django's own log statement does not
    UserExtraAttempts = apps.get_model("core", "UserExtraAttempts")
    db_alias = schema_editor.connection.alias

    for extra_attempt in UserExtraAttempts.objects.using(db_alias).all():
        instance_id = extra_attempt.inst_id
        user_id = extra_attempt.user_id

        instance_exists = WidgetInstance.objects.filter(id=instance_id).exists()
        user_exists = User.objects.filter(id=user_id).exists()

        if not instance_exists:
            print(
                f"   - Deleting UserExtraAttempt {extra_attempt.id} without matching instance '{instance_id}'"
            )
            extra_attempt.delete()
            continue
        if not user_exists:
            print(
                f"   - Deleting UserExtraAttempt {extra_attempt.id} without matching user '{user_id}'"
            )
            extra_attempt.delete()
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_merge_20250819_1026"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userextraattempts",
            name="user_extra_attempts_user_id",
        ),
        migrations.RemoveIndex(
            model_name="userextraattempts",
            name="user_extra_attempts_inst_id",
        ),
        migrations.RunPython(clean_data),
        migrations.RenameField(
            model_name="userextraattempts",
            old_name="inst_id",
            new_name="instance",
        ),
        migrations.RenameField(
            model_name="userextraattempts",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="userextraattempts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                null=False,
                related_name="extra_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userextraattempts",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                null=False,
                related_name="extra_attempts",
                to="core.widgetinstance",
            ),
        ),
    ]
