# Generated by Django 5.0.1 on 2026-03-12 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ltiplaystate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logplay',
            name='log_play_is_complete',
        ),
        migrations.AddIndex(
            model_name='logplay',
            index=models.Index(fields=['instance', 'is_complete', '-created_at', 'semester_id'], name='log_play_perf_lookup'),
        ),
    ]
