# Generated by Django 5.0.1 on 2026-04-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_usersettings_library_banned_widgetinstance_is_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetinstance',
            name='copied_from_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='core.communitylibraryentry'),
        ),
    ]
