# Generated by Django 5.0.1 on 2025-09-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_widget_featured"),
        ("core", "0028_widget_metadata_delete_widgetmetadata"),
    ]

    operations = []
