# Generated by Django 5.0.1 on 2026-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_logplay_log_play_is_complete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_TYPE", "No Type"),
                            ("PROFILE_IMAGE", "Profile Image"),
                            ("CATALOG_BANNER", "Catalog Banner"),
                        ],
                        default="NO_TYPE",
                        max_length=26,
                        null=True,
                    ),
                ),
                ("image_path", models.CharField(max_length=255)),
            ],
        ),
    ]
