# Generated by Django 5.0.1 on 2026-04-30 18:28

import os
import shutil

from django.db import migrations, models


def populate_default_profile_images(apps, schema_editor):
    """
    Adds default profile images to the SiteImage ORM
    """
    SiteImage = apps.get_model("core", "SiteImage")

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    source_dir = os.path.join(
        base_dir, "..", "..", "public", "img", "default", "profile_images"
    )
    dest_dir = os.path.join(base_dir, "staticfiles", "site_img")

    os.makedirs(dest_dir, exist_ok=True)

    default_images = [
        "aura_kogneato.png",
        "dm_kogneato.png",
        "gambit_kogneato.png",
        "in_kogneato.png",
        "kogneato_the_riveter.png",
        "metal_kogneato.png",
        "morpheus_kogneato.png",
        "shakespeare_kogneato.png",
    ]

    images_to_create = []

    for filename in default_images:
        source_path = os.path.join(source_dir, filename)
        dest_path = os.path.join(dest_dir, filename)
        image_path = f"/site_img/{filename}"

        if SiteImage.objects.filter(image_path=image_path).exists():
            continue

        if not os.path.exists(dest_path):
            if os.path.exists(source_path):
                shutil.copy2(source_path, dest_path)
            else:
                continue

        images_to_create.append(
            SiteImage(image_type="PROFILE_IMAGE", image_path=image_path)
        )

    if images_to_create:
        SiteImage.objects.bulk_create(images_to_create)


def remove_default_profile_images(apps, schema_editor):
    """
    Removes default images from the staticfiles/site_img directory.
    """
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    dest_dir = os.path.join(base_dir, "staticfiles", "site_img")

    default_images = [
        "aura_kogneato.png",
        "dm_kogneato.png",
        "gambit_kogneato.png",
        "in_kogneato.png",
        "kogneato_the_riveter.png",
        "metal_kogneato.png",
        "morpheus_kogneato.png",
        "shakespeare_kogneato.png",
    ]

    for filename in default_images:
        dest_path = os.path.join(dest_dir, filename)
        if os.path.exists(dest_path):
            try:
                os.remove(dest_path)
            except FileNotFoundError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_logplay_log_play_is_complete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_TYPE", "No Type"),
                            ("PROFILE_IMAGE", "Profile Image"),
                            ("CATALOG_BANNER", "Catalog Banner"),
                        ],
                        default="NO_TYPE",
                        max_length=26,
                        null=True,
                    ),
                ),
                ("image_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(
            populate_default_profile_images, remove_default_profile_images
        ),
    ]
