# Generated by Django 5.0.1 on 2026-04-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_widgetinstance_copied_from_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to='core.communitylibraryentry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_tagged', to='core.tag')),
            ],
            options={
                'unique_together': {('tag', 'entry')},
            },
        ),
    ]
