# Generated by Django 5.0.1 on 2026-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_siteimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_TYPE", "No Type"),
                            ("SITE_NOTIFICATION", "Site Notification"),
                            ("SITE_ALERT", "Site Alert"),
                            ("CATALOG_HEADER", "Catalog Header"),
                            ("CATALOG_TEXT", "Catalog Text"),
                        ],
                        default="NO_TYPE",
                        max_length=26,
                        null=True,
                    ),
                ),
                ("message_text", models.TextField()),
                ("start_at", models.DateTimeField(default=None, null=True)),
                ("end_at", models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
