# Generated by Django 5.0.1 on 2026-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tag_tagentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
