# Generated by Django 5.0.1 on 2026-05-08 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tag_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitylibraryentry',
            name='tags',
            field=models.ManyToManyField(through='core.TagEntry', to='core.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
