# Generated by Django 5.0.1 on 2025-10-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_merge_20250926_1522"),
        ("core", "0030_remove_userextraattempts_user_extra_attempts_user_id_and_more"),
    ]

    operations = []
