# Generated by Django 5.0.1 on 2026-07-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_library", "0002_seed_library_categories_defaults"),
        ("core", "0030_sitemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="library_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="widgetinstance",
            name="library_entry",
            field=models.ForeignKey(
                blank=True,
                db_column="library_entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copied_instances",
                to="community_library.libraryentry",
            ),
        ),
        migrations.AddField(
            model_name="widgetinstance",
            name="library_snapshot",
            field=models.ForeignKey(
                blank=True,
                db_column="library_snapshot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instance",
                to="community_library.librarysnapshot",
            ),
        ),
    ]
