# Generated by Django 5.0.1 on 2026-06-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_siteimage'),
        ('core', '0031_communitylibraryentry_tags_tag_created_at_and_more'),
    ]

    operations = [
    ]
