# Generated by Django 5.0.1 on 2025-10-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_fix_logstorage_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PermRoleToUser",
        ),
        migrations.DeleteModel(
            name="PermRoleToUserBackup",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.DeleteModel(
            name="PermObjectToUser",
        ),
        migrations.AlterModelTable(
            name="MapQuestionToQset",
            table="map_question_to_qset_old",
        ),
        migrations.AlterModelOptions(
            name="MapQuestionToQset",
            options={"managed": False},
        ),
        migrations.DeleteModel(name="MapQuestionToQset"),
    ]
