# Generated by Django 5.0.1 on 2026-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_siteimage_created_at_sitemessage_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemessage",
            name="message_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_TYPE", "No Type"),
                    ("SITE_NOTIFICATION", "Site Notification"),
                    ("SITE_ALERT", "Site Alert"),
                    ("CATALOG_HEADER", "Catalog Header"),
                    ("CATALOG_TEXT", "Catalog Text"),
                    ("LIBRARY_HEADER", "Library Header"),
                    ("LIBRARY_TEXT", "Library Text"),
                ],
                default="NO_TYPE",
                max_length=26,
                null=True,
            ),
        ),
    ]
