# Generated by Django 5.0.1 on 2025-10-06 17:52

from django.db import migrations


def create_perm_tables_if_deleted(apps, schema_editor):
    all_tables = schema_editor.connection.introspection.table_names()
    if "perm_role_to_user" not in all_tables:
        schema_editor.execute("CREATE TABLE perm_role_to_user (temp_col int null);")
    if "perm_role_to_user_backup" not in all_tables:
        schema_editor.execute(
            "CREATE TABLE perm_role_to_user_backup (temp_col int null);"
        )


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0033_fix_logstorage_data"),
    ]

    operations = [
        migrations.RunPython(create_perm_tables_if_deleted, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="PermRoleToUser",
        ),
        migrations.DeleteModel(
            name="PermRoleToUserBackup",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.DeleteModel(
            name="PermObjectToUser",
        ),
        migrations.AlterModelTable(
            name="MapQuestionToQset",
            table="map_question_to_qset_old",
        ),
        migrations.AlterModelOptions(
            name="MapQuestionToQset",
            options={"managed": False},
        ),
        migrations.DeleteModel(name="MapQuestionToQset"),
    ]
