# Generated by Django 5.0.1 on 2025-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_delete_permroletouser_delete_permroletouserbackup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectpermission",
            name="context_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
