require('./angular/controllers/ctrl-widget-creator')
require('./angular/controllers/ctrl-my-widgets-export')
require('./angular/controllers/ctrl-lti-resource-selection')
require('./angular/controllers/ctrl-media-import')
require('./angular/controllers/ctrl-my-widgets')
require('./angular/controllers/ctrl-question-import')
require('./angular/controllers/ctrl-my-widgets-collaboration')
require('./angular/controllers/ctrl-my-widgets-selected')
require('./angular/controllers/ctrl-my-widgets-settings')
require('./angular/directives/dir-beardable')
require('./angular/directives/dir-datatable')
require('./angular/directives/dir-date-validation')
require('./angular/directives/dir-filedropper')
require('./angular/directives/dir-fileonchange')
require('./angular/directives/dir-ngenter')
require('./angular/directives/dir-scoredata')
require('./angular/directives/dir-scoregraph')
require('./angular/directives/dir-scoretable')
require('./angular/filters/filter-escape')
require('./angular/filters/filter-highlight')
require('./angular/filters/filter-multiword')
require('./materia/materia.mywidgets.statistics')
require('./angular/services/srv-api')
require('./angular/services/srv-beard')
require('./angular/services/srv-scores')

// Materia Server scripts for creating content: my widgets, widget authoring, lti picker
