import React from 'react'
import ReactDOM from 'react-dom'

import MyWidgetsPage from './components/my-widgets-page'


const widgets = [
    {
        "attempts": "-1",
        "clean_name": "adsf",
        "close_at": "-1",
        "created_at": "1594431324",
        "embed_url": "http://localhost/embed/LFY6i/adsf",
        "is_student_made": false,
        "is_embedded": true,
        "embedded_only": false,
        "student_access": false,
        "guest_access": false,
        "height": 0,
        "id": "LFY6i",
        "is_draft": false,
        "name": "adsf",
        "open_at": "-1",
        "play_url": "http://localhost/play/LFY6i/adsf",
        "preview_url": "http://localhost/preview/LFY6i/adsf",
        "published_by": null,
        "user_id": "5",
        "widget": {
            "clean_name": "flash-cards",
            "creator": "creator.html",
            "created_at": "1594418703",
            "dir": "6-flash-cards/",
            "flash_version": "10",
            "api_version": "2",
            "height": "516",
            "id": "6",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "0",
            "is_storage_enabled": "0",
            "package_hash": "5f0c22fd67d9b8538ad1695163018fc9",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Media",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "Flashcards is a study tool that allows students to use a virtual deck of cards to study concepts paired with definitions or images or audio or embedded video links.",
                "excerpt": "A study tool featuring a deck of flashcards.",
                "demo": "nXwP2"
            },
            "name": "Flash Cards",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "FlashCards",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "severe-weather-survey",
        "close_at": "-1",
        "created_at": "1594418730",
        "embed_url": "http://localhost/embed/W2TPE/severe-weather-survey",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "W2TPE",
        "is_draft": false,
        "name": "Severe Weather Survey",
        "open_at": "-1",
        "play_url": "http://localhost/play/W2TPE/severe-weather-survey",
        "preview_url": "http://localhost/preview/W2TPE/severe-weather-survey",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "simple-survey",
            "creator": "creator.html",
            "created_at": "1594418730",
            "dir": "12-simple-survey/",
            "flash_version": "0",
            "api_version": "2",
            "height": "0",
            "id": "12",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "9a317a35b7be082d5973211af26b8c83",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Media"
                ],
                "supported_data": [
                    "Multiple Choice",
                    "Survey"
                ],
                "about": "Build simple surveys with multiple choice, check-all-that-apply, and free response questions.",
                "excerpt": "Build surveys or questionnaires with a range of question options including multiple choice, check-all-that-apply, and free response. Questions are not scored and students are given full credit upon completion.",
                "playdata_exporters": [
                    "Survey Formatting"
                ],
                "demo": "W2TPE"
            },
            "name": "Simple Survey",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "SurveyWidget",
            "score_screen": "scorescreen.html",
            "width": "0",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "famous-artists",
        "close_at": "-1",
        "created_at": "1594418727",
        "embed_url": "http://localhost/embed/LG4Aq/famous-artists",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "LG4Aq",
        "is_draft": false,
        "name": "Famous Artists",
        "open_at": "-1",
        "play_url": "http://localhost/play/LG4Aq/famous-artists",
        "preview_url": "http://localhost/preview/LG4Aq/famous-artists",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "sort-it-out",
            "creator": "creator.html",
            "created_at": "1594418726",
            "dir": "11-sort-it-out/",
            "flash_version": "0",
            "api_version": "2",
            "height": "650",
            "id": "11",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "3dee8dcd2eb72211af1e0b7b2a782718",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Mobile Friendly",
                    "Media"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "Sort It Out! provides items randomly spread across the screen with folders at the bottom. Students are asked to drag and drop the items into their appropriate folders.",
                "excerpt": "Students must sort items on a messy computer desktop into their appropriate folders.",
                "demo": "LG4Aq"
            },
            "name": "Sort It Out!",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "SortItOut",
            "score_screen": "scoreScreen.html",
            "width": "960",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "equation-sandbox",
        "close_at": "-1",
        "created_at": "1594418721",
        "embed_url": "http://localhost/embed/62eLw/equation-sandbox",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "62eLw",
        "is_draft": false,
        "name": "Equation Sandbox",
        "open_at": "-1",
        "play_url": "http://localhost/play/62eLw/equation-sandbox",
        "preview_url": "http://localhost/preview/62eLw/equation-sandbox",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "equation-sandbox",
            "creator": "creator.html",
            "created_at": "1594418721",
            "dir": "10-equation-sandbox/",
            "flash_version": "10",
            "api_version": "2",
            "height": "600",
            "id": "10",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "0",
            "is_storage_enabled": "0",
            "package_hash": "e6e968ca5bdcee5691a76df40bacb98c",
            "meta_data": {
                "features": [
                    "Customizable"
                ],
                "supported_data": [
                    "Custom"
                ],
                "about": "With Equation Sandbox, students will be able to experiment with the graph of an equation you create. Manipulating the variables of the equation alter the graph, allowing students to learn first-hand how a function graph is created.",
                "excerpt": "Interactive graphs from parameterized equations",
                "demo": "62eLw"
            },
            "name": "Equation Sandbox",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "EquationSandbox",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "emergency-room-care",
        "close_at": "-1",
        "created_at": "1594418715",
        "embed_url": "http://localhost/embed/4LF4q/emergency-room-care",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "4LF4q",
        "is_draft": false,
        "name": "Emergency Room Care",
        "open_at": "-1",
        "play_url": "http://localhost/play/4LF4q/emergency-room-care",
        "preview_url": "http://localhost/preview/4LF4q/emergency-room-care",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "adventure",
            "creator": "creator.html",
            "created_at": "1594418714",
            "dir": "9-adventure/",
            "flash_version": "0",
            "api_version": "2",
            "height": "593",
            "id": "9",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "c098e8c15fd542f69441b1bc8e329d5b",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Media"
                ],
                "supported_data": [
                    "Question/Answer",
                    "Multiple Choice"
                ],
                "excerpt": "Build branching scenarios where your student's choices lead them down different paths.",
                "about": "An advanced flexible scenario-building tool.",
                "playdata_exporters": [
                    "Survey Formatting"
                ],
                "demo": "4LF4q"
            },
            "name": "Adventure",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "Adventure",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "creative-writing-vocabulary",
        "close_at": "-1",
        "created_at": "1594418711",
        "embed_url": "http://localhost/embed/taJiy/creative-writing-vocabulary",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "taJiy",
        "is_draft": false,
        "name": "Creative Writing Vocabulary",
        "open_at": "-1",
        "play_url": "http://localhost/play/taJiy/creative-writing-vocabulary",
        "preview_url": "http://localhost/preview/taJiy/creative-writing-vocabulary",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "word-search",
            "creator": "creator.html",
            "created_at": "1594418711",
            "dir": "8-word-search/",
            "flash_version": "10",
            "api_version": "2",
            "height": "600",
            "id": "8",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "00bc9092b2a0affabe2d996da64c15ae",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "Word search is played by finding words in a grid of letters. Students can circle words by dragging from the start of the word to the end.",
                "excerpt": "A study tool where students must search a word puzzle for a predetermined set of words.",
                "demo": "taJiy"
            },
            "name": "Word Search",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "WordSearch",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "this-or-that",
        "close_at": "-1",
        "created_at": "1594418707",
        "embed_url": "http://localhost/embed/jzyuO/this-or-that",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "jzyuO",
        "is_draft": false,
        "name": "This or That",
        "open_at": "-1",
        "play_url": "http://localhost/play/jzyuO/this-or-that",
        "preview_url": "http://localhost/preview/jzyuO/this-or-that",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "this-or-that",
            "creator": "creator.html",
            "created_at": "1594418706",
            "dir": "7-this-or-that/",
            "flash_version": "10",
            "api_version": "2",
            "height": "515",
            "id": "7",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "b9909c870bd2d44974d25d0cfbe9d816",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Media",
                    "Scorable",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Multiple Choice"
                ],
                "about": "This or That is a game in which students must answer questions by choosing one of two images.",
                "excerpt": "Students must answer a question by choosing one of two images.",
                "demo": "jzyuO"
            },
            "name": "This Or That",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "ThisOrThat",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "psychology",
        "close_at": "-1",
        "created_at": "1594418703",
        "embed_url": "http://localhost/embed/nXwP2/psychology",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "nXwP2",
        "is_draft": false,
        "name": "Psychology",
        "open_at": "-1",
        "play_url": "http://localhost/play/nXwP2/psychology",
        "preview_url": "http://localhost/preview/nXwP2/psychology",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "flash-cards",
            "creator": "creator.html",
            "created_at": "1594418703",
            "dir": "6-flash-cards/",
            "flash_version": "10",
            "api_version": "2",
            "height": "516",
            "id": "6",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "0",
            "is_storage_enabled": "0",
            "package_hash": "5f0c22fd67d9b8538ad1695163018fc9",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Media",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "Flashcards is a study tool that allows students to use a virtual deck of cards to study concepts paired with definitions or images or audio or embedded video links.",
                "excerpt": "A study tool featuring a deck of flashcards.",
                "demo": "nXwP2"
            },
            "name": "Flash Cards",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "FlashCards",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "the-seven-continents",
        "close_at": "-1",
        "created_at": "1594418699",
        "embed_url": "http://localhost/embed/8aED2/the-seven-continents",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "8aED2",
        "is_draft": false,
        "name": "The Seven Continents",
        "open_at": "-1",
        "play_url": "http://localhost/play/8aED2/the-seven-continents",
        "preview_url": "http://localhost/preview/8aED2/the-seven-continents",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "labeling",
            "creator": "creator.html",
            "created_at": "1594418699",
            "dir": "5-labeling/",
            "flash_version": "10",
            "api_version": "2",
            "height": "601",
            "id": "5",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "9079221629921a4661d07253ee7c6334",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Media",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "In the Labeling widget, students will need to correctly place the labels that you create and add to an image of your choice. They will receive a score depending on how many correct placements they make.",
                "excerpt": "A quiz tool which requires students to correctly identify certain parts of an image by placing labels.",
                "demo": "8aED2"
            },
            "name": "Labeling",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "Labeling",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "tv-show-trivia",
        "close_at": "-1",
        "created_at": "1594418696",
        "embed_url": "http://localhost/embed/VRM5Q/tv-show-trivia",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "VRM5Q",
        "is_draft": false,
        "name": "TV Show Trivia",
        "open_at": "-1",
        "play_url": "http://localhost/play/VRM5Q/tv-show-trivia",
        "preview_url": "http://localhost/preview/VRM5Q/tv-show-trivia",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "enigma",
            "creator": "creator.html",
            "created_at": "1594418696",
            "dir": "4-enigma/",
            "flash_version": "0",
            "api_version": "2",
            "height": "548",
            "id": "4",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "90e67e2592d0d4ee07da7bdcae4b97d1",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Multiple Choice"
                ],
                "about": "Enigma is a Jeopardy-like online study and quiz tool for reviewing subject matter, concepts, and principles. Questions are separated into categorical rows.",
                "excerpt": "A Jeopardy-like study and quiz tool. Questions are separated into categorical rows.",
                "demo": "VRM5Q"
            },
            "name": "Enigma",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "EnigmaGS",
            "score_screen": "",
            "width": "750",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "spanish-verbs",
        "close_at": "-1",
        "created_at": "1594418690",
        "embed_url": "http://localhost/embed/pZxaS/spanish-verbs",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "pZxaS",
        "is_draft": false,
        "name": "Spanish Verbs",
        "open_at": "-1",
        "play_url": "http://localhost/play/pZxaS/spanish-verbs",
        "preview_url": "http://localhost/preview/pZxaS/spanish-verbs",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "matching",
            "creator": "creator.html",
            "created_at": "1594418689",
            "dir": "3-matching/",
            "flash_version": "0",
            "api_version": "2",
            "height": "548",
            "id": "3",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "9f73bf82a1a54deacf3b06e9797a3b9e",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Mobile Friendly",
                    "Media"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "Matching provides a left and a right list. Students are asked to match the items on the left with the corresponding item on the right.",
                "excerpt": "Students must match one set of words or phrases to a corresponding word, phrase, or definition.",
                "demo": "pZxaS"
            },
            "name": "Matching",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "Matching",
            "score_screen": "",
            "width": "750",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "parts-of-a-cell",
        "close_at": "-1",
        "created_at": "1594418685",
        "embed_url": "http://localhost/embed/fKenI/parts-of-a-cell",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "fKenI",
        "is_draft": false,
        "name": "Parts of a Cell",
        "open_at": "-1",
        "play_url": "http://localhost/play/fKenI/parts-of-a-cell",
        "preview_url": "http://localhost/preview/fKenI/parts-of-a-cell",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "hangman",
            "creator": "creator.html",
            "created_at": "1594418685",
            "dir": "2-hangman/",
            "flash_version": "0",
            "api_version": "2",
            "height": "620",
            "id": "2",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "525f341d63a1457e4eaec3269446ffa7",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "Hangman is a guessing game played by guessing letters in a word using the provided clues. Each wrong guess builds another part of a hanged man. Five wrong guesses and the player loses.",
                "excerpt": "Students are provided with a clue and must guess the word or phrase within a certain amount of letters.",
                "demo": "fKenI"
            },
            "name": "Hangman",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "Hangman",
            "score_screen": "",
            "width": "800",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    },
    {
        "attempts": "-1",
        "clean_name": "famous-landmarks",
        "close_at": "-1",
        "created_at": "1594418681",
        "embed_url": "http://localhost/embed/6InLM/famous-landmarks",
        "is_student_made": false,
        "is_embedded": false,
        "embedded_only": false,
        "student_access": false,
        "guest_access": true,
        "height": 0,
        "id": "6InLM",
        "is_draft": false,
        "name": "Famous Landmarks",
        "open_at": "-1",
        "play_url": "http://localhost/play/6InLM/famous-landmarks",
        "preview_url": "http://localhost/preview/6InLM/famous-landmarks",
        "published_by": null,
        "user_id": "1",
        "widget": {
            "clean_name": "crossword",
            "creator": "creator.html",
            "created_at": "1594418681",
            "dir": "1-crossword/",
            "flash_version": "10",
            "api_version": "2",
            "height": "592",
            "id": "1",
            "is_answer_encrypted": "1",
            "in_catalog": "1",
            "is_editable": "1",
            "is_playable": "1",
            "is_qset_encrypted": "1",
            "is_scalable": "0",
            "is_scorable": "1",
            "is_storage_enabled": "0",
            "package_hash": "c07c389f1316d9a97ce51c6598495e0a",
            "meta_data": {
                "features": [
                    "Customizable",
                    "Scorable",
                    "Mobile Friendly"
                ],
                "supported_data": [
                    "Question/Answer"
                ],
                "about": "In Crossword, fill in the blank squares with: (a) words based on the clues provided in the text and/or (b) by the letters overlapping from other words.",
                "excerpt": "A quiz tool that uses words and clues to randomly generate a crossword puzzle.",
                "demo": "6InLM"
            },
            "name": "Crossword",
            "player": "player.html",
            "question_types": "",
            "restrict_publish": "0",
            "score_module": "Crossword",
            "score_screen": "scoreScreen.html",
            "width": "715",
            "creator_guide": "guides/creator.html",
            "player_guide": "guides/player.html"
        },
        "width": 0,
        "qset": {
            "version": null,
            "data": null
        }
    }
]


ReactDOM.render(<MyWidgetsPage widgets={widgets} />, document.getElementById('app'))
