name: Run Tests
on: [push, pull_request]
jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Tests
      run: echo "Tests disabled temporarily"

  build_and_upload_images:
    needs: ci_tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta for Python
        id: meta_python
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/materia-django/python
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=dev,enable=${{ startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '-alpha') || contains(github.ref, '-rc')) }}

      - name: Docker meta for Nginx
        id: meta_nginx
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/materia-django/nginx
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=dev,enable=${{ startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '-alpha') || contains(github.ref, '-rc')) }}

      - name: Docker meta for FakeS3
        id: meta_fakes3
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/materia-django/fakes3
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=dev,enable=${{ startsWith(github.ref, 'refs/tags/v') && (contains(github.ref, '-alpha') || contains(github.ref, '-rc')) }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env to satisfy build requirements
        run: |
          cd docker
          if [ ! -f .env ]; then
            touch .env
          fi

      - name: Build Images
        run: |
          cd docker
          docker compose build --no-cache nginx python fakes3

      - name: Tag and Push Python Images
        run: |
          for tag in ${{ steps.meta_python.outputs.tags }}; do
            docker tag materia-django-python "$tag"
            docker push "$tag"
          done

      - name: Tag and Push Nginx Images
        run: |
          for tag in ${{ steps.meta_nginx.outputs.tags }}; do
            docker tag materia-django-nginx "$tag"
            docker push "$tag"
          done

      - name: Tag and Push FakeS3 Images
        run: |
          for tag in ${{ steps.meta_fakes3.outputs.tags }}; do
            docker tag materia-django-fakes3 "$tag"
            docker push "$tag"
          done

