# Generated by Django 5.0.1 on 2026-07-20 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0030_sitemessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("banner_path", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="LibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("introductory", "Introductory"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LibraryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate", "Inappropriate content"),
                            ("incorrect", "Incorrect content"),
                            ("spam", "Spam"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LibrarySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("qset_data", models.TextField(default="")),
                ("qset_version", models.CharField(default="1", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("normalized_name", models.CharField(max_length=50, unique=True)),
                ("used_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="librarycategory",
            constraint=models.UniqueConstraint(
                fields=("label",), name="library_category_label_unique"
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="community_library.librarycategory",
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="instance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_entry",
                to="core.widgetinstance",
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="libraryreport",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="community_library.libraryentry",
            ),
        ),
        migrations.AddField(
            model_name="libraryreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="librarysnapshot",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="community_library.libraryentry",
            ),
        ),
        migrations.AddField(
            model_name="tagentry",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged",
                to="community_library.libraryentry",
            ),
        ),
        migrations.AddField(
            model_name="tagentry",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_tagged",
                to="community_library.tag",
            ),
        ),
        migrations.AddField(
            model_name="libraryentry",
            name="tags",
            field=models.ManyToManyField(
                through="community_library.TagEntry", to="community_library.tag"
            ),
        ),
        migrations.AddField(
            model_name="userlike",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="community_library.libraryentry",
            ),
        ),
        migrations.AddField(
            model_name="userlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="libraryreport",
            unique_together={("user", "entry")},
        ),
        migrations.AddIndex(
            model_name="librarysnapshot",
            index=models.Index(
                fields=["entry", "-created_at"], name="idx_snapshot_entry_latest"
            ),
        ),
        migrations.AddConstraint(
            model_name="tagentry",
            constraint=models.UniqueConstraint(
                fields=("tag", "entry"), name="tag_entry_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="libraryentry",
            index=models.Index(fields=["-created_at"], name="idx_entry_newest"),
        ),
        migrations.AlterUniqueTogether(
            name="userlike",
            unique_together={("user", "entry")},
        ),
    ]
