# Generated by Django 5.0.1 on 2026-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_library', '0002_seed_library_categories_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycategory',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=20),
        ),
    ]
