# Generated by Django 5.0.1 on 2026-07-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_library', '0003_librarycategory_color'),
        ('core', '0031_usersettings_library_banned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarysnapshot',
            name='qset_data',
        ),
        migrations.RemoveField(
            model_name='librarysnapshot',
            name='qset_version',
        ),
        migrations.AddField(
            model_name='librarysnapshot',
            name='qset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='core.widgetqset'),
            preserve_default=False,
        ),
    ]
